In [1]:
#%% Libraries
import torch

##### Ex. 1.1: Creating a column vector I
Use the following properties:
* Shape of 3 x 1
* Data type of 64-bit floating point
* Device on CPU
* Non-learnable parameter


In [3]:
a = torch.zeros((3, 1), dtype=torch.float64, device='cpu', requires_grad=False)

print(a)
print(a.shape)


tensor([[0.],
        [0.],
        [0.]], dtype=torch.float64)
torch.Size([3, 1])


##### Ex. 1.2: Creating a column vector II

In [5]:


# Create the following column vector using the function torch.tensor
# ans
a = torch.tensor(([1],[3],[5]), dtype=torch.float32) 

print(a.shape)

torch.Size([3, 1])


##### Ex. 1.3: Creating a row vector

In [17]:
b = torch.tensor([[1, 3, 5]], dtype=torch.float32)
print(b.shape)

torch.Size([1, 3])


##### Ex. 1.4: Creating a matrix

In [18]:

A = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=torch.float32)
print(A.shape)

torch.Size([3, 4])


##### Ex. 1.5: Creating a 3D-matrix 

In [22]:
A_ = torch.tensor([[[1,2],[5,6],[9,10]],[[3,4],[7,8],[11,12]]], dtype=torch.float)
print(A_.shape)

torch.Size([2, 3, 2])


#### Ex. 2.1: Manipulating elements


##### Ex. 2.1.1: For vector

In [25]:
z = torch.zeros(3,1)
z[0] = 1

print(z)

tensor([[1.],
        [0.],
        [0.]])


##### Ex. 2.1.2: For matrix

In [57]:
Z = torch.zeros(3,4)
Z[0, 2] = 1

print(Z)

tensor([[0., 0., 1., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


##### Ex. 2.1.3: For 3D matrix

In [29]:
Z_ = torch.zeros(2, 3, 4)
Z_[1,1,2] = 1
Z_

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 0.]]])

#### Ex. 2.1.4: Slicing I

In [47]:
print(Z_[1,:,[2]])

tensor([[0.],
        [1.],
        [0.]])


##### Ex. 2.1.5: Slicing II

In [51]:
print(Z_[1,:,[1,2]])

tensor([[0., 0.],
        [0., 1.],
        [0., 0.]])


##### Ex. 2.1.6: Slicing III

In [44]:
print(Z_[1,:,[1,2,3]])

tensor([[0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])


#### Ex. 2.2: Stacking and concatenate

##### Ex. 2.2.1: Stacking vectors to matrices

In [76]:

a = torch.tensor([[1],[3],[5]], dtype=torch.float) 
b = torch.tensor([[2],[4],[6]], dtype=torch.float)

c = torch.stack((a,b), dim=2)
                
print(c)

tensor([[[1., 2.]],

        [[3., 4.]],

        [[5., 6.]]])


##### Ex. 2.2.2: Concatenate vectors

In [65]:

a = torch.tensor([[1],[3],[5]], dtype=torch.float) 
b = torch.tensor([[2],[4],[6]], dtype=torch.float)

c = torch.cat((a,b), dim=0)
c

tensor([[1.],
        [3.],
        [5.],
        [2.],
        [4.],
        [6.]])

##### Ex. 2.3: Transpose

##### Ex. 2.3.1: Transpose vectors

In [80]:
a = torch.tensor([[1],[3],[5]], dtype=torch.float) 
b = torch.transpose(a,0,1)
b

tensor([[1., 3., 5.]])

##### Ex. 2.3.2: Transpose II

In [84]:
A = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=torch.float) 
B = torch.transpose(A,0,1)
B 


tensor([[ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.],
        [ 4.,  8., 12.]])

##### Ex. 2.3.3: Transpose III 

In [92]:
A_ = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]], dtype=torch.float) 

B_ = torch.transpose(A_,1,2)
B_

tensor([[[ 1.,  5.,  9.],
         [ 2.,  6., 10.],
         [ 3.,  7., 11.],
         [ 4.,  8., 12.]],

        [[ 1.,  5.,  9.],
         [ 2.,  6., 10.],
         [ 3.,  7., 11.],
         [ 4.,  8., 12.]]])

#### Ex. 2.4: Element-wise Multiplication

##### Ex. 2.4.1: Vector

In [94]:
a = torch.tensor([[2],[3],[5]], dtype=torch.float) 
b = torch.tensor([[2],[3],[5]], dtype=torch.float) 

c = a*b
c

tensor([[ 4.],
        [ 9.],
        [25.]])

##### Ex. 2.4.2: Matrix

In [96]:

A = torch.tensor([[2,3,4],[5,6,7]], dtype=torch.float) 
B = torch.tensor([[2,3,4],[5,6,7]], dtype=torch.float) 

C = A*B
C

tensor([[ 4.,  9., 16.],
        [25., 36., 49.]])

##### Ex. 2.4.3: Broadcasting

In [99]:
a = torch.tensor([[2],[3],[5]], dtype=torch.float) 
b = torch.transpose(a,0,1)
c= a*b
c

tensor([[ 4.,  6., 10.],
        [ 6.,  9., 15.],
        [10., 15., 25.]])

##### Ex. 2.4.4: No code

##### Ex. 2.5.1: Matrix multiplication

In [103]:
A = torch.tensor([[2,3,4], [5,6,7]], dtype=torch.float32)
B = torch.tensor([[2,3,4], [5,6,7]], dtype=torch.float32)
B_ = torch.transpose(B,0,1)
C = torch.matmul(A,B_)
C

tensor([[ 29.,  56.],
        [ 56., 110.]])

##### Ex. 2.5.2: Matrix multiplication with broadcasting 



In [106]:
A_ = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]], dtype=torch.float) 

B = torch.tensor([[1,5,9], [2,6,10], [3,7,11],[4,8,12]], dtype=torch.float32)

C_ = torch.matmul(A_,B)
C_

tensor([[[ 30.,  70., 110.],
         [ 70., 174., 278.],
         [110., 278., 446.]],

        [[ 30.,  70., 110.],
         [ 70., 174., 278.],
         [110., 278., 446.]]])